### ISSUE TITLE
Built-in ways to open SM

### ISSUE THREAD

**Issue by jfcherng** [FloydaGithub/open-smerge#1]
Just an FYI.

There is a built-in ST command to open SM. For example,
```
{ "keys": ["alt+shift+o", "alt+shift+m"], "command": "sublime_merge_open_repo" },
```

Or, click on the branch icon at the bottom bar.

![image](https://user-images.githubusercontent.com/6594915/55664480-31acf000-5861-11e9-8889-cd9dd4894f19.png)

**Comment by floydawong** [comment]
This package was developed before the built-in functionality -_-!!!

**Comment by jfcherng** [comment]
Never mind. Just a FYI in case people don't know it.

**Comment by floydawong** [comment]
3Q, the same is ST lover.
